### PR TITLE
#1103 Improvment configuration events

### LINKED ISSUE #1103: Improvment configuration events
## Expected Behavior
Based on the configuration, whether or not the problem with sending emails will show up in alarm list.

## Actual Behavior

If there is a problem with sending email, the information is about it displayed by default on the alarm list, which causes a complete lack of readability alarm list which is troubled by the system problem.

## Steps to Reproduce the Problem

1. Create report 
2. Set report send by email
3. Set wrong config for send emails

## Specifications

  - Version: v2.1.0
  - Platform: linux
  - Subsystem: open jdk 1.8, mysql 5.7, nodejs 8.12.0

## The problem reported by:
@grzesiekb

### PR DESCRIPTION
**Pull request by grzesiekb**
I added configuration in env.properties DO_NOT_CREATE_EVETS_EVETS_FOR_EMAIL_ERROR is a switch based on which problem with sending emails is generated event or saved to the log.
DO_NOT_CREATE_EVETS_FOR_EMAIL_ERROR=false
When parameter have value  **true** then saves the problem with sending an e-mail to the log (log4j)
When parameter have value  **false** then the problem with sending an e-mail generates an event.

fix #1103

### CODE REVIEW

File: WebContent/WEB-INF/classes/env.properties [hunk 1]
```diff
@@ -74,6 +74,8 @@ abilit.USE_CACHE_DATA_SOURCES_POINTS_WHEN_THE_SYSTEM_IS_READY=true
 abilit.USE_ACL=false
 abilit.ACL_SERVER=http://localhost:8090
 
+#Events
+abilit.DONT_CREATE_EVETS_FOR_EMAIL_ERROR=false
```
Comment (mateuszhyski) [inline WebContent/WEB-INF/classes/env.properties]: Is it possible to rename this flag , it means, by just put char 'N' :
DONT_CREATE_EVETS_FOR_EMAIL_ERROR  -> DONT_CREATE_EVENTS_FOR_EMAIL_ERROR

File: src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java [hunk 2]
```diff
@@ -90,15 +98,24 @@ public void execute() {
...
             String to = "";
             for (InternetAddress addr : toAddresses) {
                 if (to.length() > 0)
                     to += ", ";
                 to += addr.getAddress();
             }
-            SystemEventType.raiseEvent(new SystemEventType(SystemEventType.TYPE_EMAIL_SEND_FAILURE),
-                    System.currentTimeMillis(), false,
-                    new LocalizableMessage("event.email.failure", subject, to, e.getMessage()));
+            Boolean dontCreateEventForEmailError = false;
```
Comment (mateuszhyski) [inline src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java]: Wow, great, I mean I understand sense of variable.

File: src/org/scada_lts/config/ScadaConfig.java [hunk 3]
```diff
@@ -136,6 +136,10 @@
 
 	private Optional<Integer> optimizationLevelJs = Optional.empty();
 
+	public static final String DONT_CREATE_EVETS_FOR_EMAIL_ERROR = "abilit.DONT_CREATE_EVETS_FOR_EMAIL_ERROR";
```
Comment (mateuszhyski) [inline src/org/scada_lts/config/ScadaConfig.java]: Is it possible to rename this variable , it means, by just put char 'N' :
DONT_CREATE_EVETS_FOR_EMAIL_ERROR - > DONT_CREATE_EVENTS_FOR_EMAIL_ERROR

File: src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java [hunk 4]
```diff
@@ -90,15 +98,24 @@ public void execute() {
...
+            try {
+                dontCreateEventForEmailError = ScadaConfig.getInstance().getBoolean(ScadaConfig.DONT_CREATE_EVETS_FOR_EMAIL_ERROR,false);
```
Comment (mateuszhyski) [inline src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java]: Is it possible to rename this variable , it means, by just put char 'N' :
DONT_CREATE_EVETS_FOR_EMAIL_ERROR - > DONT_CREATE_EVENTS_FOR_EMAIL_ERROR

File: src/org/scada_lts/config/ScadaConfig.java [hunk 5]
```diff
@@ -214,6 +218,8 @@ public Boolean getBoolean(String propertyName, boolean defaultValue) {
 				return useACL.get();
 			} else if (HTTP_RETRIVER_DO_NOT_ALLOW_ENABLE_REACTIVATION.equals(propertyName) && httpRetriverDoNotAllowEnableReactivation.isPresent()) {
 				return httpRetriverDoNotAllowEnableReactivation.get();
+			} else if (DONT_CREATE_EVETS_FOR_EMAIL_ERROR.equals(propertyName) && dontCreateEventsForEmailError.isPresent()) {
+				return dontCreateEventsForEmailError.get();
```
Comment (mateuszhyski) [inline src/org/scada_lts/config/ScadaConfig.java]: Is it possible to rename this variable , it means, by just put char 'N' :
DONT_CREATE_EVETS_FOR_EMAIL_ERROR - > DONT_CREATE_EVENTS_FOR_EMAIL_ERROR

File: src/org/scada_lts/config/ScadaConfig.java [hunk 6]
```diff
@@ -226,6 +232,8 @@ public Boolean getBoolean(String propertyName, boolean defaultValue) {
 					useACL = Optional.of(result);
 				} else if (HTTP_RETRIVER_DO_NOT_ALLOW_ENABLE_REACTIVATION.equals(propertyName)) {
 					httpRetriverDoNotAllowEnableReactivation = Optional.of(result);
+				} else if (DONT_CREATE_EVETS_FOR_EMAIL_ERROR.equals(propertyName)) {
+					dontCreateEventsForEmailError = Optional.of(result);
```
Comment (mateuszhyski) [inline src/org/scada_lts/config/ScadaConfig.java]: Is it possible to rename this variable , it means, by just put char 'N' :
DONT_CREATE_EVETS_FOR_EMAIL_ERROR - > DONT_CREATE_EVENTS_FOR_EMAIL_ERROR

That's all

File: WebContent/WEB-INF/classes/env.properties (hunk 1 above)
Comment (grzesiekb) [reply WebContent/WEB-INF/classes/env.properties]: Instead of adding char, "N" suggests DO_NOT_CREATE_EVETS_FOR_EMAIL_ERROR

Comment (mateuszhyski) [reply WebContent/WEB-INF/classes/env.properties]: Ok

File: src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java [hunk 7]
```diff
@@ -90,15 +98,24 @@ public void execute() {
...
+            } catch (IOException er) {
+                LOG.error(er);
+            }
+            if (!dontCreateEventForEmailError) {
+                SystemEventType.raiseEvent(new SystemEventType(SystemEventType.TYPE_EMAIL_SEND_FAILURE),
+                        System.currentTimeMillis(), false,
```
[the remark this answers is not in the document]
Comment (grzesiekb) [reply src/com/serotonin/mango/rt/maint/work/EmailWorkItem.java]: I can change it
